Map<String, String> ar = {
  "skip": "تخطى",
  "continue": "متابعة",
  "language": "اللغة",
  "ar": "اللغة العربية",
  "en": "English",
  "fr": "Français",
  "looks_like_you're_offline": "يبدو أنك غير متصل بالإنترنت !!",
  "make_sure_you_are_connected_first": "تأكد من إتصال جهازك بالإنترنت أولاً",
  "login": "تسجيل الدخول",
  "logout": "تسجيل الخروج",
  "notifications": "الإشعارات",
  "chat_rooms": "غرف المحادثة",
  "profile": "الملف الشخصى",
  "are_u_sure_to_sign_out": "هل أنت متأكد من تسجيل الخروج؟",
  "you_will_need_to_login_next_time_you_use_the_app":
      "ستحتاج لتسجيل الدخول مجدداً فى المرة المقبلة التى تستخدم فيها التطبيق",
  "edit": "تعديل",
  "cancel": "إلغاء",
  "confirm": "تأكيد",
  "settings": "الإعدادات",
  "Preferences": "التفضيلات",
  "dark_mode": "الوضع المظلم",
  'select_a_user_type': 'اختر نوع المستخدم',
  'username': 'اسم المستخدم',
  'password': 'كلمة المرور',
  'remember_me': 'تــذكرنـى',
};
