Map<String, String> ar = {
  "skip": "تخطى",
  "continue": "متابعة",
  "language": "اللغة",
  "ar": "اللغة العربية",
  "en": "English",
  "fr": "Français",
  'good_morning': 'صباح الخير',
  'good_evening': 'مساء الخير ',
  'good_afternoon': 'مساء الخير',
  "looks_like_you're_offline": "يبدو أنك غير متصل بالإنترنت !!",
  "make_sure_you_are_connected_first": "تأكد من إتصال جهازك بالإنترنت أولاً",
  "login": "تسجيل الدخول",
  "logout": "تسجيل الخروج",
  "notifications": "الإشعارات",
  "chat_rooms": "غرف المحادثة",
  "profile": "الملف الشخصى",
  "are_u_sure_to_sign_out": "هل أنت متأكد من تسجيل الخروج؟",
  "you_will_need_to_login_next_time_you_use_the_app":
      "ستحتاج لتسجيل الدخول مجدداً فى المرة المقبلة التى تستخدم فيها التطبيق",
  "edit": "تعديل",
  "cancel": "إلغاء",
  "confirm": "تأكيد",
  "settings": "الإعدادات",
  "Preferences": "التفضيلات",
  "dark_mode": "الوضع المظلم",
  'select_a_user_type': 'اختر نوع المستخدم',
  'username': 'اسم المستخدم',
  'identifier': 'identifier',
  'password': 'كلمة المرور',
  'remember_me': 'تــذكرنـى',
  'please_select_user_type': 'من فضلك اختر نوع المستخدم',
  'search': 'بحث',
  'no_result_title': 'لا توجد نتيجة',
  'no_result_body':
      'عذرا، لا توجد أية نتيجة تتعلق بهذا البحث. يرجى تجربة عبارة أخرى'
};
