Map<String, String> en = {
  "skip": "Skip",
  "continue": "Continue",
  "ar": "اللغة العربية",
  "en": "English",
  "fr": "Français",
  "looks_like_you're_offline": "Looks Like You Are Offline !!",
  "make_sure_you_are_connected_first": "Make Sure You Are Connected first",
  "login": "Login",
  "logout": "Logout",
  "notifications": "Notifications",
  "chat_rooms": "Chat Rooms",
  "profile": "Profile",
  "are_u_sure_to_sign_out": "Are You Sure to Logout?",
  "you_will_need_to_login_next_time": "You Will need to login again next time",
  "cancel": "Cancel",
  "confirm": "Confirm",
};
