Map<String, String> en = {
  "skip": "Skip",
  "continue": "Continue",
  "language": "Language",
  "ar": "اللغة العربية",
  "en": "English",
  "fr": "Français",
  "looks_like_you're_offline": "Looks Like You Are Offline !!",
  "make_sure_you_are_connected_first": "Make Sure You Are Connected first",
  "login": "Login",
  "logout": "Logout",
  "notifications": "Notifications",
  "chat_rooms": "Chat Rooms",
  "profile": "Profile",
  "are_u_sure_to_sign_out": "Are You Sure to Logout?",
  "you_will_need_to_login_next_time_you_use_the_app":
      "You Will need to login again next time You use the App",
  "edit": "Edit",
  "cancel": "Cancel",
  "confirm": "Confirm",
  "settings": "Settings",
  "Preferences": "Preferences",
  "dark_mode": "Dark Mode",
  'select_a_user_type': 'Select a user type',
  'username': 'Username',
  'password': 'Password',
  'remember_me': 'Remember me',
};
