Map<String, String> fr = {
  "skip": "Sauter",
  "continue": "Continuez",
  "language": "Langue",
  "ar": "اللغة العربية",
  "en": "English",
  "fr": "Français",
  'good_morning': 'Bonjour',
  'good_evening': 'bonsoir',
  'good_afternoon': 'bonne après-midi',
  "looks_like_you're_offline": "On dirait que vous êtes hors ligne !!",
  "make_sure_you_are_connected_first":
      "Assurez-vous d'abord que vous êtes connecté",
  "login": "Connexion",
  "logout": "se déconnecter",
  "notifications": "Notifications",
  "chat_rooms": "Salons de discussion",
  "profile": "Profil",
  "are_u_sure_to_sign_out": "êtes-vous sûr de vous déconnecter?",
  "you_will_need_to_login_next_time_you_use_the_app":
      "Vous devrez vous reconnecter la prochaine fois que vous utiliserez l'application",
  "edit": "Éditer",
  "cancel": "annuler",
  "confirm": "Confirmer",
  "settings": "Réglages",
  "Preferences": "Préférences",
  "dark_mode": "mode sombre",
  'select_a_user_type': 'Select a user type',
  'username': 'Username',
  'password': 'Password',
  'identifier': 'identifier',
  'remember_me': 'Remember me',
  'please_select_user_type': 'please select user type',
  'search': 'rechercher'
};
