name: schooleverywhereV2
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment:
  sdk: ">=2.18.0 <3.0.0"

dependencies:
  cupertino_icons: ^1.0.2
  get: 4.6.5
  flutter:
    sdk: flutter
  flutter_svg: ^1.1.5
  badges: ^2.0.3
  shared_preferences: ^2.0.15
  firebase_core: ^1.12.0
  google_maps_flutter: ^2.2.0
  firebase_messaging: ^12.0.1
  geolocator: ^9.0.1
  location: ^4.3.0
  flutter_downloader: ^1.8.4

  connectivity_plus: ^3.0.2
  dio: ^4.0.6
  flutter_launcher_icons: ^0.11.0

dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/
    - img/
